import javax.swing.*;
import java.awt.event.*;
import java.sql.*;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Lenovo
 */
public class editproduk extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(editproduk.class.getName());

    /**
     * Creates new form editproduk
     */
    public editproduk(String idp, String namaproduk, String jenisproduk, String harga, String stok) {
        initComponents();
        setLocationRelativeTo(null);
        
        txtid_produk.setText(idp);
        txtnamaproduk.setText(namaproduk);
        txtjenisproduk.setText(jenisproduk);
        txthargaproduk.setText(harga);
        txtstokproduk.setText(stok);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtid_produk = new javax.swing.JTextField();
        txtnamaproduk = new javax.swing.JTextField();
        txtjenisproduk = new javax.swing.JTextField();
        txthargaproduk = new javax.swing.JTextField();
        txtstokproduk = new javax.swing.JTextField();
        Jtombolsimpanproduk = new javax.swing.JButton();
        Jtombolbatalproduk = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 255));

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Edit Produk");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setText("Id_Produk :");

        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel3.setText("Nama :");

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel4.setText("Jenis :");

        jLabel5.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel5.setText("Harga :");

        jLabel6.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel6.setText("Stok :");

        txtid_produk.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N

        txtnamaproduk.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N

        txtjenisproduk.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        txtjenisproduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtjenisprodukActionPerformed(evt);
            }
        });

        txthargaproduk.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        txthargaproduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthargaprodukActionPerformed(evt);
            }
        });

        txtstokproduk.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N

        Jtombolsimpanproduk.setText("Simpan");
        Jtombolsimpanproduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtombolsimpanprodukActionPerformed(evt);
            }
        });

        Jtombolbatalproduk.setText("Batal");
        Jtombolbatalproduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtombolbatalprodukActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(106, 106, 106))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Jtombolbatalproduk)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                        .addComponent(Jtombolsimpanproduk))
                    .addComponent(txtid_produk, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtjenisproduk, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtnamaproduk, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txthargaproduk, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtstokproduk, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtid_produk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtnamaproduk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtjenisproduk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txthargaproduk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtstokproduk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jtombolsimpanproduk)
                    .addComponent(Jtombolbatalproduk))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtjenisprodukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtjenisprodukActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtjenisprodukActionPerformed

    private void txthargaprodukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthargaprodukActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txthargaprodukActionPerformed

    private void JtombolbatalprodukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtombolbatalprodukActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_JtombolbatalprodukActionPerformed

    private void JtombolsimpanprodukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtombolsimpanprodukActionPerformed
        // TODO add your handling code here:
        try {
            String id_produk = txtid_produk.getText();
            String nama_produk = txtnamaproduk.getText();
            String jenis_produk = txtjenisproduk.getText();
            String harga_produk = txthargaproduk.getText();
            String stok_produk = txtstokproduk.getText();
            
            Connection conn = koneksi.getConnection();
            
            String sql = "UPDATE produk SET nama=?, jenis=?, harga=?, stok=? WHERE id_produk=?";
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, nama_produk);
            pst.setString(2, jenis_produk);
            pst.setString(3, harga_produk);
            pst.setString(4, stok_produk);
            pst.setString(5, id_produk);
            
            int hasil = pst.executeUpdate();
            
            if (hasil > 0) {
                JOptionPane.showMessageDialog(this, "Data berhasil disimpan!");
                dispose(); // menutup form edit_data setelah simpan
            } else {
                JOptionPane.showMessageDialog(this, "Gagal menyimpan data!");
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage());
        }
    }//GEN-LAST:event_JtombolsimpanprodukActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Jtombolbatalproduk;
    private javax.swing.JButton Jtombolsimpanproduk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txthargaproduk;
    private javax.swing.JTextField txtid_produk;
    private javax.swing.JTextField txtjenisproduk;
    private javax.swing.JTextField txtnamaproduk;
    private javax.swing.JTextField txtstokproduk;
    // End of variables declaration//GEN-END:variables
}
